from django.db import models
from django.contrib.auth.models import User
from dam.models import Dam


class HydroAlert(models.Model):
    SEVERITY_LEVELS = [
        ('LOW', 'Low Priority'),
        ('MEDIUM', 'Medium Priority'),
        ('HIGH', 'High Priority'),
        ('CRITICAL', 'Critical Priority'),
    ]
    
    ALERT_TYPES = [
        ('FLOOD', 'Flood Warning'),
        ('DROUGHT', 'Drought Warning'),
        ('WATER_QUALITY', 'Water Quality Alert'),
        ('STRUCTURAL', 'Structural Integrity Alert'),
        ('WEATHER', 'Weather-Related Alert'),
    ]
    
    dam = models.ForeignKey(Dam, on_delete=models.CASCADE, related_name='hydro_alerts')
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES)
    severity = models.CharField(max_length=10, choices=SEVERITY_LEVELS)
    title = models.CharField(max_length=200)
    message = models.TextField()
    affected_areas = models.TextField(help_text="List of affected areas")
    recommended_actions = models.TextField(help_text="Recommended actions to take")
    water_level = models.FloatField(help_text="Current water level in mcft")
    rainfall_amount = models.FloatField(default=0, help_text="Rainfall amount in mm")
    temperature = models.FloatField(null=True, blank=True, help_text="Temperature in Celsius")
    is_active = models.BooleanField(default=True)
    auto_generated = models.BooleanField(default=True, help_text="Whether alert was auto-generated by system")
    created_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)
    acknowledged_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='acknowledged_alerts')
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['dam', '-created_at']),
            models.Index(fields=['alert_type']),
            models.Index(fields=['severity']),
            models.Index(fields=['is_active']),
        ]
    
    def __str__(self):
        return f"{self.dam.name} - {self.severity} {self.alert_type}: {self.title}"


class AlertSubscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='alert_subscriptions')
    dam = models.ForeignKey(Dam, on_delete=models.CASCADE, related_name='subscribers')
    alert_types = models.JSONField(default=list, help_text="List of alert types user is subscribed to")
    severity_levels = models.JSONField(default=list, help_text="List of severity levels user wants to receive")
    email_notifications = models.BooleanField(default=True)
    sms_notifications = models.BooleanField(default=False)
    webhook_url = models.URLField(blank=True, help_text="Webhook URL for custom notifications")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['user', 'dam']
        unique_together = ['user', 'dam']
        indexes = [
            models.Index(fields=['user', 'is_active']),
            models.Index(fields=['dam', 'is_active']),
        ]
    
    def __str__(self):
        return f"{self.user.username} - {self.dam.name} subscriptions"


class AlertNotification(models.Model):
    NOTIFICATION_TYPES = [
        ('EMAIL', 'Email Notification'),
        ('SMS', 'SMS Notification'),
        ('WEBHOOK', 'Webhook Notification'),
        ('IN_APP', 'In-App Notification'),
    ]
    
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('SENT', 'Sent'),
        ('FAILED', 'Failed'),
        ('RETRY', 'Retry Scheduled'),
    ]
    
    alert = models.ForeignKey(HydroAlert, on_delete=models.CASCADE, related_name='notifications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='alert_notifications')
    notification_type = models.CharField(max_length=10, choices=NOTIFICATION_TYPES)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='PENDING')
    recipient = models.CharField(max_length=200, help_text="Email, phone number, or webhook URL")
    message_content = models.TextField()
    sent_at = models.DateTimeField(null=True, blank=True)
    error_message = models.TextField(blank=True)
    retry_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['alert', '-created_at']),
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['status']),
            models.Index(fields=['notification_type']),
        ]
    
    def __str__(self):
        return f"{self.user.username} - {self.notification_type} for {self.alert.title}"


class WeatherThreshold(models.Model):
    dam = models.ForeignKey(Dam, on_delete=models.CASCADE, related_name='weather_thresholds')
    threshold_name = models.CharField(max_length=100)
    rainfall_threshold_24h = models.FloatField(help_text="Rainfall threshold for 24 hours in mm")
    rainfall_threshold_3d = models.FloatField(help_text="Rainfall threshold for 3 days in mm")
    temperature_threshold_min = models.FloatField(help_text="Minimum temperature threshold in Celsius")
    temperature_threshold_max = models.FloatField(help_text="Maximum temperature threshold in Celsius")
    wind_speed_threshold = models.FloatField(help_text="Wind speed threshold in km/s")
    humidity_threshold_min = models.FloatField(help_text="Minimum humidity threshold percentage")
    humidity_threshold_max = models.FloatField(help_text="Maximum humidity threshold percentage")
    alert_severity = models.CharField(max_length=10, choices=HydroAlert.SEVERITY_LEVELS)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['dam', 'threshold_name']
        unique_together = ['dam', 'threshold_name']
        indexes = [
            models.Index(fields=['dam', 'is_active']),
        ]
    
    def __str__(self):
        return f"{self.dam.name} - {self.threshold_name}"


class HistoricalAlert(models.Model):
    dam = models.ForeignKey(Dam, on_delete=models.CASCADE, related_name='historical_alerts')
    alert_date = models.DateField()
    alert_type = models.CharField(max_length=20, choices=HydroAlert.ALERT_TYPES)
    severity = models.CharField(max_length=10, choices=HydroAlert.SEVERITY_LEVELS)
    description = models.TextField()
    water_level_at_alert = models.FloatField(help_text="Water level at time of alert in mcft")
    rainfall_24h = models.FloatField(default=0, help_text="Rainfall in 24 hours before alert in mm")
    estimated_damage = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    affected_population = models.IntegerField(null=True, blank=True)
    resolution_time_hours = models.FloatField(null=True, blank=True, help_text="Time taken to resolve alert in hours")
    lessons_learned = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-alert_date']
        indexes = [
            models.Index(fields=['dam', '-alert_date']),
            models.Index(fields=['alert_type']),
            models.Index(fields=['severity']),
            models.Index(fields=['alert_date']),
        ]
    
    def __str__(self):
        return f"{self.dam.name} - {self.alert_date}: {self.severity} {self.alert_type}"
