# Generated by Django 5.0.7 on 2026-03-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.FloatField(help_text='Maximum water capacity in mcft')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dam_dam_name_0a1882_idx'), models.Index(fields=['location'], name='dam_dam_locatio_08f98f_idx'), models.Index(fields=['is_active'], name='dam_dam_is_acti_159766_idx')],
            },
        ),
        migrations.CreateModel(
            name='DamAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH', 'High Water Level Alert'), ('LOW', 'Low Water Level Alert'), ('NORMAL', 'Normal Status'), ('CRITICAL', 'Critical Alert')], max_length=10)),
                ('message', models.TextField()),
                ('water_level', models.FloatField(help_text='Water level at time of alert in mcft')),
                ('inflow_rate', models.FloatField(help_text='Inflow rate at time of alert in cubic feet/sec')),
                ('rainfall_last_3_days', models.FloatField(default=0, help_text='Total rainfall in last 3 days in mm')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dam.dam')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dam', '-created_at'], name='dam_damaler_dam_id_7b71e4_idx'), models.Index(fields=['alert_type'], name='dam_damaler_alert_t_9849d8_idx'), models.Index(fields=['is_active'], name='dam_damaler_is_acti_a64118_idx')],
            },
        ),
        migrations.CreateModel(
            name='DamMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField()),
                ('upstream_water_level', models.FloatField(help_text='Upstream water level in mcft')),
                ('downstream_water_level', models.FloatField(help_text='Downstream water level in mcft')),
                ('inflow_rate', models.FloatField(help_text='Inflow rate in cubic feet/sec')),
                ('outflow_rate', models.FloatField(help_text='Outflow rate in cubic feet/sec')),
                ('rainfall_amount', models.FloatField(default=0, help_text='Rainfall amount in mm')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed km/s', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dam.dam')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'indexes': [models.Index(fields=['dam', '-measurement_date'], name='dam_dammeas_dam_id_735709_idx'), models.Index(fields=['measurement_date'], name='dam_dammeas_measure_8ddab3_idx')],
                'unique_together': {('dam', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='DamOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('RELEASE', 'Water Release'), ('STORAGE', 'Water Storage'), ('MONITOR', 'Monitoring Only'), ('EMERGENCY', 'Emergency Operation')], max_length=10)),
                ('water_release_amount', models.FloatField(blank=True, help_text='Amount of water released in mcft', null=True)),
                ('recommended_release', models.FloatField(help_text='Recommended water release in mcft')),
                ('inflow_capacity', models.FloatField(help_text='Current inflow capacity in cubic feet/sec')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='dam.dam')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dam', '-created_at'], name='dam_damoper_dam_id_cce289_idx'), models.Index(fields=['operation_type'], name='dam_damoper_operati_d4d676_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField()),
                ('model_type', models.CharField(default='RandomForest', max_length=50)),
                ('features_used', models.JSONField(help_text='Features used for prediction')),
                ('prediction_result', models.BooleanField(help_text='True for success, False for failure')),
                ('confidence_score', models.FloatField(help_text='Model confidence score')),
                ('actual_result', models.BooleanField(blank=True, help_text='Actual outcome for validation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dam.dam')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['dam', '-prediction_date'], name='dam_mlmodel_dam_id_0ee633_idx'), models.Index(fields=['model_type'], name='dam_mlmodel_model_t_9b688f_idx'), models.Index(fields=['prediction_date'], name='dam_mlmodel_predict_f739c9_idx')],
            },
        ),
    ]
