# Generated by Django 5.0.7 on 2026-03-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=10)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', '-timestamp'], name='weather_wea_city_602bf3_idx'), models.Index(fields=['timestamp'], name='weather_wea_timesta_7bce59_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-search_timestamp'],
                'indexes': [models.Index(fields=['user', '-search_timestamp'], name='weather_use_user_id_e40a89_idx'), models.Index(fields=['city'], name='weather_use_city_a39971_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=10)),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.weatherdata')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('weather_data', 'date')},
            },
        ),
    ]
