# Generated by Django 5.0.7 on 2026-03-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HydroAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FLOOD', 'Flood Warning'), ('DROUGHT', 'Drought Warning'), ('WATER_QUALITY', 'Water Quality Alert'), ('STRUCTURAL', 'Structural Integrity Alert'), ('WEATHER', 'Weather-Related Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('affected_areas', models.TextField(help_text='List of affected areas')),
                ('recommended_actions', models.TextField(help_text='Recommended actions to take')),
                ('water_level', models.FloatField(help_text='Current water level in mcft')),
                ('rainfall_amount', models.FloatField(default=0, help_text='Rainfall amount in mm')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_generated', models.BooleanField(default=True, help_text='Whether alert was auto-generated by system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydro_alerts', to='dam.dam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email Notification'), ('SMS', 'SMS Notification'), ('WEBHOOK', 'Webhook Notification'), ('IN_APP', 'In-App Notification')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRY', 'Retry Scheduled')], default='PENDING', max_length=10)),
                ('recipient', models.CharField(help_text='Email, phone number, or webhook URL', max_length=200)),
                ('message_content', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hydroalert.hydroalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_name', models.CharField(max_length=100)),
                ('rainfall_threshold_24h', models.FloatField(help_text='Rainfall threshold for 24 hours in mm')),
                ('rainfall_threshold_3d', models.FloatField(help_text='Rainfall threshold for 3 days in mm')),
                ('temperature_threshold_min', models.FloatField(help_text='Minimum temperature threshold in Celsius')),
                ('temperature_threshold_max', models.FloatField(help_text='Maximum temperature threshold in Celsius')),
                ('wind_speed_threshold', models.FloatField(help_text='Wind speed threshold in km/s')),
                ('humidity_threshold_min', models.FloatField(help_text='Minimum humidity threshold percentage')),
                ('humidity_threshold_max', models.FloatField(help_text='Maximum humidity threshold percentage')),
                ('alert_severity', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_thresholds', to='dam.dam')),
            ],
            options={
                'ordering': ['dam', 'threshold_name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_types', models.JSONField(default=list, help_text='List of alert types user is subscribed to')),
                ('severity_levels', models.JSONField(default=list, help_text='List of severity levels user wants to receive')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for custom notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='dam.dam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'dam'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='hydroalert__user_id_f429b0_idx'), models.Index(fields=['dam', 'is_active'], name='hydroalert__dam_id_b24819_idx')],
                'unique_together': {('user', 'dam')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField()),
                ('alert_type', models.CharField(choices=[('FLOOD', 'Flood Warning'), ('DROUGHT', 'Drought Warning'), ('WATER_QUALITY', 'Water Quality Alert'), ('STRUCTURAL', 'Structural Integrity Alert'), ('WEATHER', 'Weather-Related Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], max_length=10)),
                ('description', models.TextField()),
                ('water_level_at_alert', models.FloatField(help_text='Water level at time of alert in mcft')),
                ('rainfall_24h', models.FloatField(default=0, help_text='Rainfall in 24 hours before alert in mm')),
                ('estimated_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('affected_population', models.IntegerField(blank=True, null=True)),
                ('resolution_time_hours', models.FloatField(blank=True, help_text='Time taken to resolve alert in hours', null=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_alerts', to='dam.dam')),
            ],
            options={
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['dam', '-alert_date'], name='hydroalert__dam_id_c3033e_idx'), models.Index(fields=['alert_type'], name='hydroalert__alert_t_3ad8b8_idx'), models.Index(fields=['severity'], name='hydroalert__severit_b4fdb1_idx'), models.Index(fields=['alert_date'], name='hydroalert__alert_d_7fb6e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hydroalert',
            index=models.Index(fields=['dam', '-created_at'], name='hydroalert__dam_id_f0a3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='hydroalert',
            index=models.Index(fields=['alert_type'], name='hydroalert__alert_t_9be08c_idx'),
        ),
        migrations.AddIndex(
            model_name='hydroalert',
            index=models.Index(fields=['severity'], name='hydroalert__severit_fdecab_idx'),
        ),
        migrations.AddIndex(
            model_name='hydroalert',
            index=models.Index(fields=['is_active'], name='hydroalert__is_acti_075090_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['alert', '-created_at'], name='hydroalert__alert_i_6a8cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['user', '-created_at'], name='hydroalert__user_id_b15039_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status'], name='hydroalert__status_71c348_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['notification_type'], name='hydroalert__notific_7c92a1_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherthreshold',
            index=models.Index(fields=['dam', 'is_active'], name='hydroalert__dam_id_b9b547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherthreshold',
            unique_together={('dam', 'threshold_name')},
        ),
    ]
